(add-hook 'objc-mode-hook
          (lambda ()
            (define-key objc-mode-map "\C-c\C-b" 'compile)
            (define-key objc-mode-map "\C-c\C-r" 'run)
            (define-key objc-mode-map "\C-c\C-x" 'xcode)
            (define-key objc-mode-map "\C-c\C-d" 'doc)
            (define-key objc-mode-map "\C-c\C-c" 'comment-region)
            (define-key objc-mode-map "\C-cc"    'uncomment-region)
            (setq compile-command "xcodebuild -project ../*.xcodeproj -configuration Debug -sdk iphonesimulator6.0 ")
            (setq compilation-scroll-output t)))
(defun doc ()
	(interactive)
  (shell-command-to-string "~/bin/xcode-show-doc.sh"))
(defun xcode ()
	(interactive)
  (shell-command-to-string "~/bin/xcode-show-proj.sh"))
(defun run ()
  (interactive)
  (shell-command-to-string "~/bin/xcode-run.sh"))
